version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    build: ./api
    restart: always
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: password
      MYSQL_DB: time_db
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql
  nginx:  
    depends_on:
      - api
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

volumes:
  mysql_data:
